import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { motion, useMotionValue, useReducedMotion, useSpring, useTransform } from 'motion/react'
import { GraduationCap, KeyRound, ShieldCheck } from 'lucide-react'
import { useApp } from '../store/AppStore'
import { api } from '../lib/api'
import { landingRoute } from '../lib/landingRoute'
import { takePendingPassword } from '../lib/pendingPassword'
import { Button } from '../components/ui'
import { useDocumentTitle } from '../hooks/useDocumentTitle'

// Shown once, right after an invited member's first sign-in: the password they
// used was generated by us and mailed to them in the clear, so this offers to
// replace it while that's still fresh. Skippable by design — the backend flag
// only prompts, it never gates access, and Settings has the same form forever.
//
// Login passes the password they just typed through router state so this
// screen doesn't ask for it twice. Landing here directly (a refresh, or a
// bookmark) has no such state, so it asks for the current password instead of
// dead-ending.

/** One star: position/size/timing fixed at mount so they don't jump on rerender. */
interface Star {
  top: string
  left: string
  size: number
  dim: number
  lit: number
  dur: string
  delay: string
  depth: number
}

function useStars(count: number): Star[] {
  return useMemo(
    () =>
      Array.from({ length: count }, () => {
        const depth = Math.random()
        return {
          top: `${Math.random() * 100}%`,
          left: `${Math.random() * 100}%`,
          // Nearer stars (higher depth) read as bigger and brighter.
          size: 1 + depth * 1.8,
          dim: 0.15 + depth * 0.2,
          lit: 0.45 + depth * 0.5,
          dur: `${3 + Math.random() * 4}s`,
          delay: `${Math.random() * 5}s`,
          depth,
        }
      }),
    [count],
  )
}

export function SetPassword() {
  useDocumentTitle('Set your password · Root Connect')
  const navigate = useNavigate()
  const { currentUser, notify } = useApp()
  const reduced = useReducedMotion()

  // The password typed on the sign-in screen a moment ago, if we got here the
  // intended way. Held in a module variable, not router state, so it is never
  // serialised into window.history — which means a reload legitimately loses
  // it and the `needsCurrent` fallback below takes over, as intended.
  // useState's initialiser runs once, so the read-and-clear happens once.
  const [passedCurrent] = useState(takePendingPassword)
  const [current, setCurrent] = useState(passedCurrent)
  const [next, setNext] = useState('')
  const [confirm, setConfirm] = useState('')
  const [error, setError] = useState<string | null>(null)
  const [saving, setSaving] = useState(false)
  const needsCurrent = !passedCurrent

  // --- cursor parallax -----------------------------------------------------
  // Normalised to -1..1 from the viewport centre, then spring-damped so the
  // scene trails the pointer instead of snapping to it.
  const mx = useMotionValue(0)
  const my = useMotionValue(0)
  const sx = useSpring(mx, { stiffness: 45, damping: 18, mass: 0.6 })
  const sy = useSpring(my, { stiffness: 45, damping: 18, mass: 0.6 })

  useEffect(() => {
    if (reduced) return
    function onMove(e: PointerEvent) {
      mx.set((e.clientX / window.innerWidth) * 2 - 1)
      my.set((e.clientY / window.innerHeight) * 2 - 1)
    }
    window.addEventListener('pointermove', onMove, { passive: true })
    return () => window.removeEventListener('pointermove', onMove)
  }, [mx, my, reduced])

  // Each layer moves a different amount — that difference is the depth cue.
  const farX = useTransform(sx, (v) => v * -14)
  const farY = useTransform(sy, (v) => v * -14)
  const midX = useTransform(sx, (v) => v * -30)
  const midY = useTransform(sy, (v) => v * -30)
  const glowX = useTransform(sx, (v) => v * -60)
  const glowY = useTransform(sy, (v) => v * -46)

  const farStars = useStars(90)
  const midStars = useStars(45)

  async function save(e: React.FormEvent) {
    e.preventDefault()
    if (next.length < 6) return setError('Your new password must be at least 6 characters.')
    if (next !== confirm) return setError('The two passwords do not match.')
    if (needsCurrent && !current) return setError('Enter the password from your invitation email.')
    setError(null)
    setSaving(true)
    try {
      await api.changePassword(current, next)
      notify('Password updated — use your new one from now on.')
      navigate(landingRoute(currentUser), { replace: true })
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Could not update the password.')
      setSaving(false)
    }
  }

  const field =
    'w-full rounded-xl border border-white/10 bg-white/[0.04] px-4 py-3 text-sm text-white placeholder-white/35 outline-none transition-colors focus:border-brand focus:bg-white/[0.07] focus:ring-2 focus:ring-brand/25'

  return (
    <div className="relative min-h-screen overflow-hidden bg-scrim">
      {/* ---- animated backdrop ---- */}
      <div aria-hidden className="pointer-events-none absolute inset-0">
        {/* ambient orange glows, drifting slowly behind everything */}
        <motion.div style={{ x: glowX, y: glowY }} className="absolute inset-0">
          <div className="drift-slow absolute -left-32 -top-40 h-[34rem] w-[34rem] rounded-full bg-brand/20 blur-[120px]" />
          <div
            className="drift-slow absolute -bottom-48 -right-24 h-[30rem] w-[30rem] rounded-full bg-marigold/12 blur-[120px]"
            style={{ animationDelay: '-11s' }}
          />
        </motion.div>

        {/* far starfield — smallest parallax shift */}
        <motion.div style={{ x: farX, y: farY }} className="absolute inset-0">
          {farStars.map((s, i) => (
            <span
              key={i}
              className="star"
              style={{
                top: s.top,
                left: s.left,
                width: s.size,
                height: s.size,
                ['--star-dim' as string]: s.dim,
                ['--star-lit' as string]: s.lit,
                ['--star-dur' as string]: s.dur,
                ['--star-delay' as string]: s.delay,
              }}
            />
          ))}
        </motion.div>

        {/* near starfield — moves noticeably more */}
        <motion.div style={{ x: midX, y: midY }} className="absolute inset-0">
          {midStars.map((s, i) => (
            <span
              key={i}
              className="star"
              style={{
                top: s.top,
                left: s.left,
                width: s.size * 1.5,
                height: s.size * 1.5,
                ['--star-dim' as string]: s.dim,
                ['--star-lit' as string]: s.lit,
                ['--star-dur' as string]: s.dur,
                ['--star-delay' as string]: s.delay,
              }}
            />
          ))}
        </motion.div>

        {/* vignette so the card always has contrast under it */}
        <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_center,transparent_35%,rgba(0,0,0,0.65)_100%)]" />
      </div>

      {/* ---- content ---- */}
      <div className="relative mx-auto flex min-h-screen max-w-6xl flex-col justify-center px-6 py-12 lg:px-12">
        <motion.div
          initial={reduced ? undefined : { opacity: 0, y: 18 }}
          animate={reduced ? undefined : { opacity: 1, y: 0 }}
          transition={{ duration: 0.5, ease: [0.22, 1, 0.36, 1] }}
          className="w-full max-w-lg"
        >
          <div className="mb-8 inline-flex items-center gap-2.5">
            <span className="grid h-10 w-10 place-items-center rounded-lg bg-brand text-white">
              <GraduationCap size={22} />
            </span>
            <span className="text-sm font-semibold text-white/60">Rooman Alumni Network</span>
          </div>

          <h1 className="text-3xl font-bold leading-tight text-white sm:text-4xl">
            Make this account yours.
          </h1>
          <p className="mt-3 text-[15px] leading-relaxed text-white/55">
            You signed in with a password we generated and emailed you. Set your own now so that one
            stops working.
          </p>

          <div className="mt-8 rounded-2xl border border-white/10 bg-white/[0.03] p-6 backdrop-blur-xl sm:p-7">
            <div className="mb-5 flex items-center gap-2 text-sm font-semibold text-white">
              <KeyRound size={16} className="text-brand" /> Choose a new password
            </div>

            <form onSubmit={save} className="space-y-3" noValidate>
              {needsCurrent && (
                <input
                  className={field}
                  type="password"
                  placeholder="Password from your invitation email"
                  autoComplete="current-password"
                  value={current}
                  onChange={(e) => setCurrent(e.target.value)}
                />
              )}
              <input
                className={field}
                type="password"
                placeholder="New password (min 6 characters)"
                autoComplete="new-password"
                autoFocus={!needsCurrent}
                value={next}
                onChange={(e) => setNext(e.target.value)}
              />
              <input
                className={field}
                type="password"
                placeholder="Confirm new password"
                autoComplete="new-password"
                value={confirm}
                onChange={(e) => setConfirm(e.target.value)}
              />

              {error && (
                <p
                  role="alert"
                  className="rounded-xl border border-red-500/25 bg-red-500/10 px-3 py-2 text-sm font-medium text-red-300"
                >
                  {error}
                </p>
              )}

              <Button type="submit" className="w-full" loading={saving}>
                Save password
              </Button>
            </form>

            <div className="mt-5 border-t border-white/10 pt-4 text-center">
              <button
                type="button"
                onClick={() => navigate(landingRoute(currentUser), { replace: true })}
                className="text-sm font-semibold text-white/70 transition-colors hover:text-white"
              >
                Skip for now
              </button>
              <p className="mt-1.5 text-xs text-white/40">
                You can change your password anytime from Settings.
              </p>
            </div>
          </div>

          <p className="mt-6 flex items-center justify-center gap-1.5 text-xs text-white/35">
            <ShieldCheck size={13} /> Your email address stays as your sign-in identity.
          </p>
        </motion.div>
      </div>
    </div>
  )
}
